#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>

// first triangle number to have over 500 divisors
// nth triangle number: generated by adding n first natural numbers

int main() {

	int ndiv=0, num=0, i=0, j;

	while( ndiv <500){
				
		ndiv=0;
		i++;
		num+=i;
		
//		if (num < 500) continue;

		for (j=1; j<=num; j++)
			if( num%j == 0) {
				ndiv++;
				if( num/j == j) {ndiv = ndiv*2-1; break;}
				if( num/j < j) {ndiv = (ndiv-1)*2; break;}
			}

	}
	
	printf("num: %d ndiv: %d", num, ndiv);

	return 0;
}
